# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black = '#01060E'
red = '#EA6C73'
green = '#7FD962'
yellow = '#F9AF4F'
blue = '#53BDFA'
magenta = '#CDA1FA'
cyan = '#90E1C6'
white = '#C7C7C7'

# Bright colors
[colors.bright]
black = '#686868'
red = '#F07178'
green = '#AAD94C'
yellow = '#FFB454'
blue = '#59C2FF'
magenta = '#D2A6FF'
cyan = '#95E6CB'
white = '#FFFFFF'
