import = ["~/.config/alacritty/themes/themes/ayu_dark.toml"]

[env]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10
decorations = "buttonless"
opacity = 0.60
blur = true

option_as_alt = "Both"

[font]
normal.family = "ZedMono Nerd Font"
size = 16

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "t"
mods = "Command"
